# Site wide configuration

title:            James Hill [.io]
locale:           en_GB
# url:              http://jameshill.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: James Hill
  avatar: http://www.gravatar.com/avatar/0ca116552960ee81fc5d01a6cfab2705.png
  bio: "Salesforce developer in NZ with a more than passing interest in the quantified self, diabetic tech, and home automation"
  email: me@jameshill.io
  disqus-shortname: oblongmana
  twitter: Oblongmana
  facebook: #username
  google:
    plus: #username
    analytics: UA-42284973-1
    verify:    lhFALdqslbVT035aD2czmncrp2vFj9MFIDqyPaS6UCk
    ad-client:
    ad-slot:
  bing-verify:
  github: Oblongmana
  stackoverflow: 1575561/james-hill
  linkedin: jameshillnz
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
